### ISSUE TITLE
Registration deadline may be misleading in some places.

### ISSUE THREAD

**Issue by RichardJFoster** [aj-foster/region-manager#19]
I just noticed something which may cause folk confusion. It's not directly an issue with Region Manager, but the integration between Region Manager and the [Florida FTC Events](https://www.flfirst.org/events) page. (Loving the new sites, by the way. So much better than last season.)

On flfirst.org, the stated registration window for the Gulf Coast League's Scrimmage is `Aug 27, 2024 - Oct 22, 2024`. Folk are likely to assume that means 23:59:59 on Oct 22nd, but in Region Manager it's showing as 23:59:59 on Oct 21st. I.e. 00:00:00 on October 22nd is too late.

Because folk typically mean "end of day" when they specify dates, might it be appropriate to adjust the "registration close" date to be the user specified date (which is likely to be the last date for which registration is accepted) + 1 day - 1 second?

**Comment by aj-foster** [comment]
cc @jschool504

**Comment by jschool504** [comment]
@RichardJFoster Thanks for reporting this! This turned out to be an issue with these dates being incorrectly shown in UTC time.

If you check the website now, you should see that the registration close dates line up with Region Manager (in the example you provided, the Gulf Coast Scrimmage is now show as the registration closing date having been 10/21/2024). Hopefully this will be a little more clear and, if anything, lead folks to register on or before the final day of registration.

Please reach out if you have any questions or additional feedback!

**Comment by RichardJFoster** [comment]
@jschool504 UTC, huh? If I had a dollar for every time I'd made a similar mistake... well I wouldn't be rich, but I'd have at last $10 more, because apparently I didn't learn my lesson the first time it happened! Thank you for looking into the issue. I can confirm that for all the events I looked at there is no longer a discrepancy so I'll close out this case.
